import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="w-full  md:grid md:grid-cols-2">
      <Image
        src={
          "https://res.cloudinary.com/dcotr8wpa/image/upload/v1722456173/tienda/image-login/hero-image-4_nmccxp.jpg"
        }
        width={500}
        height={500}
        alt="image-login"
        className=" w-full object-cover h-screen hidden md:block"
      />
      {children}
    </div>
  );
}
